<?php
if (!defined('ABSPATH')) {
	exit; // Prevent access directly
}

if (function_exists('acf_add_local_field_group')) {

	acf_add_local_field_group(array(
		'key' => 'group_60f79414a135f',
		'title' => 'Featured content',
		'fields' => array(
			array(
				'key' => 'field_60fa313db50d9',
				'label' => 'Block header',
				'name' => 'block_header',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => 150,
			),
			array(
				'key' => 'field_60fa2d1adc807',
				'label' => 'Featured item',
				'name' => 'featured_item',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 2,
				'max' => 3,
				'layout' => 'block',
				'button_label' => '',
				'sub_fields' => array(
					array(
						'key' => 'field_60f794e192a94',
						'label' => 'Title',
						'name' => 'title',
						'type' => 'text',
						'instructions' => 'The title of the featured content.',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => 150,
					),
					array(
						'key' => 'field_60fa2d803d5ad',
						'label' => 'Image',
						'name' => 'img',
						'type' => 'image',
						'instructions' => 'Recommended size is 1600x1080 px. Images that include text are not recommended, as it might be cropped or blocked.',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'id',
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'min_width' => 800,
						'min_height' => '',
						'min_size' => '',
						'max_width' => 3000,
						'max_height' => '',
						'max_size' => '',
						'mime_types' => 'png,jpg',
					),
					array(
						'key' => 'field_60fa2d803d5ae',
						'label' => 'Link',
						'name' => 'link',
						'type' => 'link',
						'instructions' => 'The link can be an internal page or external url (a link is required)',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/featured',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_6100a1b1b8db0',
		'title' => 'OEG Media and text with a link',
		'fields' => array(
			array(
				'key' => 'field_6100a21101fcf',
				'label' => 'Title',
				'name' => 'mt_title',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => 'Write a title for this block',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_6100a23401fd0',
				'label' => 'Description',
				'name' => 'mt_description',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => 250,
				'rows' => 3,
				'new_lines' => 'wpautop',
			),
			array(
				'key' => 'field_6100a1c101fce',
				'label' => 'Background image',
				'name' => 'media_img',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => 1200,
				'min_height' => '',
				'min_size' => '',
				'max_width' => 3000,
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_6100a26d20eab',
				'label' => 'Link',
				'name' => 'mt_link',
				'type' => 'link',
				'instructions' => 'Choose a page link or paste the URL (optional)',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
			),
			array(
				'key' => 'field_61046c173434a',
				'label' => 'Background color',
				'name' => 'bg_color',
				'type' => 'color_picker',
				'instructions' => 'Choose a color for the background if not using an image.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#153ca4',
			),
			array(
				'key' => 'field_6104943a2488d',
				'label' => 'Full Width Toggle',
				'name' => 'full_toggle',
				'type' => 'true_false',
				'instructions' => 'Choose if this block is going to be full-screen width or contained inside the content area.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'message' => 'Full Width',
				'default_value' => 1,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/oeg-hero-banner',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_610b595988896',
		'title' => 'Personas',
		'fields' => array(
			array(
				'key' => 'field_610b5a715baa0',
				'label' => 'Personas',
				'name' => 'personas',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 1,
				'max' => 0,
				'layout' => 'block',
				'button_label' => '',
				'sub_fields' => array(
					array(
						'key' => 'field_610b596b00856',
						'label' => 'Photo',
						'name' => 'photo',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => 'editor-pic',
							'id' => '',
						),
						'return_format' => 'id',
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'min_width' => 600,
						'min_height' => '',
						'min_size' => '',
						'max_width' => 1200,
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array(
						'key' => 'field_611348e09e454',
						'label' => 'Information',
						'name' => 'lines',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_610b5ab75baa1',
								'label' => 'Line 1',
								'name' => 'line1',
								'type' => 'text',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => 'line1',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => 'Example: Ale José Yunuen',
								'prepend' => '',
								'append' => '',
								'maxlength' => 140,
							),
							array(
								'key' => 'field_610b5f9bc7ebf',
								'label' => 'Line 2',
								'name' => 'line2',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_610b5ab75baa1',
											'operator' => '!=empty',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => 'Example: Collection Development Librarian',
								'prepend' => '',
								'append' => '',
								'maxlength' => 140,
							),
							array(
								'key' => 'field_61109bbe789ff',
								'label' => 'Line 3',
								'name' => 'line3',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_610b5f9bc7ebf',
											'operator' => '!=empty',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => 'Example: United Kingdom',
								'prepend' => '',
								'append' => '',
								'maxlength' => 140,
							),
						),
					),
					array(
						'key' => 'field_61109c5ce400f',
						'label' => 'Link',
						'name' => 'profile_link',
						'type' => 'link',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/oeg-people-grid',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_611db72503245',
		'title' => 'OEG Post list',
		'fields' => array(
			array(
				'key' => 'field_611db8cfdd23d',
				'label' => 'Post item',
				'name' => 'post_item',
				'type' => 'relationship',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => '',
				'taxonomy' => '',
				'filters' => array(
					0 => 'search',
					1 => 'post_type',
					2 => 'taxonomy',
				),
				'elements' => array(
					0 => 'featured_image',
				),
				'min' => 1,
				'max' => 20,
				'return_format' => 'object',
			),
			array(
				'key' => 'field_611f1b524013a',
				'label' => 'List or Grid',
				'name' => 'list_grid',
				'type' => 'button_group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'grid' => 'Grid',
					'list' => 'List',
				),
				'allow_null' => 0,
				'default_value' => 'Grid',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
			array(
				'key' => 'field_611db91ddd23e',
				'label' => 'Featured image',
				'name' => 'feat_img',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'message' => 'Show featured image',
				'default_value' => 1,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_611db950dd23f',
				'label' => 'Date',
				'name' => 'date',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '40',
					'class' => '',
					'id' => '',
				),
				'message' => 'Show date',
				'default_value' => 1,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_611db970dd240',
				'label' => 'Excerpt',
				'name' => 'excerpt',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'message' => 'Show excerpt',
				'default_value' => 1,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_611db989dd241',
				'label' => 'Category',
				'name' => 'category',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'message' => 'Show Category',
				'default_value' => 1,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/oeg-posts-list',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	// Playlist fields
	acf_add_local_field_group(array(
		'key' => 'group_612be4ca61ac9',
		'title' => 'Playlist',
		'fields' => array(
			array(
				'key' => 'field_612be87f97861',
				'label' => 'Playlist',
				'name' => 'playlist',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_612be5e147139',
				'min' => 1,
				'max' => 0,
				'layout' => 'table',
				'button_label' => '',
				'sub_fields' => array(
					array(
						'key' => 'field_612c06d6d9b2c',
						'label' => 'Audio Title',
						'name' => 'audio_title',
						'type' => 'text',
						'instructions' => 'Please add the audio title here.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_612be5e147139',
						'label' => 'Audio URL',
						'name' => 'audio_url',
						'type' => 'url',
						'instructions' => 'Please add the audio URL here.',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/oeg-playlist',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	// Testimonials
	acf_add_local_field_group(array(
		'key' => 'group_619fbba12e6c1',
		'title' => 'Testimonial Slider',
		'fields' => array(
			array(
				'key' => 'field_619fbbb9cdba2',
				'label' => 'Testimonial',
				'name' => 'testimonial',
				'type' => 'repeater',
				'instructions' => 'Add testimonials here...',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 1,
				'max' => 10,
				'layout' => 'row',
				'button_label' => 'Add testimonial',
				'sub_fields' => array(
					array(
						'key' => 'field_619fbc05cdba3',
						'label' => 'Quote',
						'name' => 'quote',
						'type' => 'textarea',
						'instructions' => 'Write or paste your text here...',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Education is what remains after one has forgotten what one has learned in school.',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => 5,
						'new_lines' => 'wpautop',
					),
					array(
						'key' => 'field_619fbc6fcdba4',
						'label' => 'Name',
						'name' => 'name',
						'type' => 'text',
						'instructions' => 'Write or paste the quote\'s author here...',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Albert Einstein',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => 80,
					),
					array(
						'key' => 'field_619fbc9ecdba5',
						'label' => 'Author\'s info',
						'name' => 'info',
						'type' => 'textarea',
						'instructions' => 'Write or paste the person\'s occupation or location here...',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Federal polytechnic school in Zurich (Federal teaching diploma, 1900). University of Zurich (PhD, 1905)',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => 3,
						'new_lines' => '',
					),
					array(
						'key' => 'field_619fbcf2cdba6',
						'label' => 'Photo',
						'name' => 'photo',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => 'ts-thumb',
							'id' => '',
						),
						'return_format' => 'id',
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'min_width' => 200,
						'min_height' => '',
						'min_size' => '',
						'max_width' => 1500,
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array(
						'key' => 'field_619fc2659c742',
						'label' => 'cite',
						'name' => 'cite',
						'type' => 'url',
						'instructions' => 'Paste the link to the reference here...',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
				),
			),
			array(
				'key' => 'field_619feb64585f3',
				'label' => 'Background Color',
				'name' => 'bg_color',
				'type' => 'color_picker',
				'instructions' => 'Select the background color for the testimonial block',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
			),
			array(
				'key' => 'field_61a65b4874600',
				'label' => 'Text color',
				'name' => 'text_color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#333333',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/oeg-testimonial-slider',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
}
